// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // Replace this comment with your code
		int N = Integer.parseInt(args[0]);
		int greaterThanHalf = 0;
		int lessThanOrEqualToHalf = 0;

		for (int i = 0; i< N; i++) {
			double randomValue = Math.random();
			if (randomValue > 0.5){
				greaterThanHalf = greaterThanHalf + 1;
			} else {
				lessThanOrEqualToHalf = lessThanOrEqualToHalf + 1;
			}


		}
		System.out.println("> 0.5: " + greaterThanHalf + " times");
		System.out.println("> 0.5: " + lessThanOrEqualToHalf + " times");
		System.out.println("Ratio: " + (double) greaterThanHalf / lessThanOrEqualToHalf);
 

	}
}
